- name: Stop and remove all Docker containers
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Get list of all containers
      community.docker.docker_container_info:
        gather_subset:
          - all
      register: docker_info

    - name: Stop containers
      community.docker.docker_container:
        name: "{{ item.Name }}"
        state: stopped
      loop: "{{ docker_info.containers }}"
      when: docker_info.containers | length > 0

    - name: Remove containers
      community.docker.docker_container:
        name: "{{ item.Name }}"
        state: absent
        force_kill: true
      loop: "{{ docker_info.containers }}"
      when: docker_info.containers | length > 0
