---
- name: Deploy all docker applications
  hosts: all
  become: true
  roles:
    - docker

  vars_files:
    - vars/vars.yml
    - vars/vault.yml

- name: Watchtower
  ansible.builtin.import_playbook: docker/watchtower.yml
- name: Autoheal
  ansible.builtin.import_playbook: docker/autoheal.yml
- name: Vpn
  ansible.builtin.import_playbook: docker/vpn.yml
- name: Treafik
  ansible.builtin.import_playbook: docker/traefik.yml
- name: Cooking
  ansible.builtin.import_playbook: docker/cooking.yml
- name: Calibre web
  ansible.builtin.import_playbook: docker/calibre-web.yml
- name: Calibre
  ansible.builtin.import_playbook: docker/calibre.yml
- name: Homeassitant
  ansible.builtin.import_playbook: docker/homeassistant.yml
- name: Jellfyin
  ansible.builtin.import_playbook: docker/jellyfin.yml
- name: Ombi
  ansible.builtin.import_playbook: docker/ombi.yml
- name: Prowlarr
  ansible.builtin.import_playbook: docker/prowlarr.yml
- name: Qbittorrent
  ansible.builtin.import_playbook: docker/qbittorrent.yml
- name: Radarr
  ansible.builtin.import_playbook: docker/radarr.yml
- name: Grocy
  ansible.builtin.import_playbook: docker/grocy.yml
- name: Readarr
  ansible.builtin.import_playbook: docker/readarr.yml
- name: Speakarr
  ansible.builtin.import_playbook: docker/speakarr.yml
- name: Lidarr
  ansible.builtin.import_playbook: docker/lidarr.yml
- name: Reddit
  ansible.builtin.import_playbook: docker/reddit-top-rss.yml
- name: Sonarr
  ansible.builtin.import_playbook: docker/sonarr.yml
- name: Tdarr
  ansible.builtin.import_playbook: docker/tdarr.yml
- name: Uptime Kuma
  ansible.builtin.import_playbook: docker/uptime-kuma.yml
- name: Grafana
  ansible.builtin.import_playbook: docker/grafana.yml
- name: Prometheus
  ansible.builtin.import_playbook: docker/prometheus.yml
- name: Homepage
  ansible.builtin.import_playbook: docker/homepage.yml
- name: Bazarr
  ansible.builtin.import_playbook: docker/bazarr.yml
- name: Nextcloud
  ansible.builtin.import_playbook: docker/nextcloud.yml
