---
- name: Deploy all docker applications
  hosts: all
  become: true
  roles:
    - docker

  vars_files:
    - vars/vars.yml
    - vars/vault.yml

- name: WUD
  ansible.builtin.import_playbook: docker/wud.yml
- name: Autoheal
  ansible.builtin.import_playbook: docker/autoheal.yml
- name: Vpn
  ansible.builtin.import_playbook: docker/vpn.yml
- name: Treafik
  ansible.builtin.import_playbook: docker/traefik.yml
- name: LLDAP
  ansible.builtin.import_playbook: docker/lldap.yml
- name: Authelia
  ansible.builtin.import_playbook: docker/authelia.yml
- name: Cooking
  ansible.builtin.import_playbook: docker/cooking.yml
- name: Calibre web
  ansible.builtin.import_playbook: docker/calibre-web.yml
- name: Calibre
  ansible.builtin.import_playbook: docker/calibre.yml
- name: Homeassitant
  ansible.builtin.import_playbook: docker/homeassistant.yml
- name: Jellfyin
  ansible.builtin.import_playbook: docker/jellyfin.yml
- name: Ombi
  ansible.builtin.import_playbook: docker/ombi.yml
- name: Prowlarr
  ansible.builtin.import_playbook: docker/prowlarr.yml
- name: Qbittorrent
  ansible.builtin.import_playbook: docker/qbittorrent.yml
- name: Radarr
  ansible.builtin.import_playbook: docker/radarr.yml
- name: Grocy
  ansible.builtin.import_playbook: docker/grocy.yml
- name: Flaresolverr
  ansible.builtin.import_playbook: docker/flaresolverr.yml
- name: Lidarr
  ansible.builtin.import_playbook: docker/lidarr.yml
- name: Sonarr
  ansible.builtin.import_playbook: docker/sonarr.yml
- name: Tdarr
  ansible.builtin.import_playbook: docker/tdarr.yml
- name: Gatus
  ansible.builtin.import_playbook: docker/gatus.yml
- name: Grafana
  ansible.builtin.import_playbook: docker/grafana.yml
- name: Loki
  ansible.builtin.import_playbook: docker/loki.yml
- name: Promtail
  ansible.builtin.import_playbook: docker/promtail.yml
- name: Node Exporter
  ansible.builtin.import_playbook: docker/node-exporter.yml
- name: CAdvisor
  ansible.builtin.import_playbook: docker/cadvisor.yml
- name: Prometheus
  ansible.builtin.import_playbook: docker/prometheus.yml
- name: Homepage
  ansible.builtin.import_playbook: docker/homepage.yml
- name: Bazarr
  ansible.builtin.import_playbook: docker/bazarr.yml
- name: Purgarr
  ansible.builtin.import_playbook: docker/purgarr.yml
- name: Recyclarr
  ansible.builtin.import_playbook: docker/recyclarr.yml
