---
- name: Setup
  hosts: all
  become: true
  roles:
    - docker

  vars_files: vars/vault.yml

  tasks:
    - name: Run the equivalent of "pacman -Sy" as a separate step
      ansible.builtin.package:
        update_cache: true

    - name: Ensure sshfs is installed.
      ansible.builtin.package:
        name: sshfs
        state: present

    - name: Ensure NAS mount point directory exists
      ansible.builtin.file:
        path: "{{ docker_nas }}"
        state: directory
        mode: "0755"

      # Run sshfs locally on the machine TODO: Look into doing this automatically

    - name: Configure NAS SSHFS mount in fstab
      ansible.posix.mount:
        path: "{{ docker_nas }}"
        src: "{{ nas_user }}@{{ nas_ip }}:/"
        fstype: fuse.sshfs
        opts: "noauto,x-systemd.automount,_netdev,reconnect,identityfile=/home/tobins/.ssh/id_ed25519,allow_other,default_permissions"
        boot: false
        state: present
      notify: Reboot for NAS mount

  handlers:
    - name: Reboot for NAS mount
      ansible.builtin.reboot:
