---
- hosts: all
  become: true
  roles:
    - docker
    - htpasswd

  vars_files: vars/vault.yml

  tasks:
    - name: Run the equivalent of "pacman -Sy" as a separate step
      ansible.builtin.package:
        update_cache: true

    - name: Ensure sshfs is installed.
      ansible.builtin.package:
        name: sshfs
        state: present

    - name: Check if nas is already defined in the fstab
      ansible.builtin.lineinfile:
        state: absent
        path: "/etc/fstab"
        regexp: "^{{ nas_user }}@{{ nas_ip }}"
      check_mode: true
      changed_when: false # This just makes things look prettier in the logs
      register: check

      # Run sshfs locally on the machine TODO: Look into doing this automatically

    - name: Define nas mount if undefined
      ansible.builtin.lineinfile:
        state: present
        path: "/etc/fstab"
        line: "{{ nas_user }}@{{ nas_ip }}:/ {{ docker_nas }} fuse.sshfs noauto,x-systemd.automount,_netdev,reconnect,identityfile=/home/tobins/.ssh/id_ed25519,allow_other,default_permissions 0 0"
      when: check.found == 0

    - name: Reboot if nas mount was undefined
      reboot:
      when: check.found == 0
