---
- name: Upgrade system
  hosts: all
  become: true
  become_user: root

  vars_files: vars/vault.yml

  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    - name: Upgrade all packages on debian servers
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        upgrade: true
        force_apt_get: true
    - name: Upgrade all packages on arch servers
      when: ansible_os_family == 'Archlinux'
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
    - name: Reboot the box if kernel updated
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 90
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
