---
- name: Rsync copy docker var
  ansible.posix.synchronize:
    src: /var/lib/docker/
    dest: /home/docker

- name: Stop docker
  ansible.builtin.service:
    name: docker
    state: stopped

- name: Recursively remove docker directory
  ansible.builtin.file:
    path: /var/lib/docker
    state: absent

- name: Create a symbolic link
  ansible.builtin.file:
    src: /var/lib/docker/
    dest: /home/docker
    owner: root
    group: root
    state: link
    force: true

- name: Start docker
  ansible.builtin.service:
    name: docker
    state: started
