---
- name: Calibre Web
  vars:
    service: "calibre-web"
    labels:
      - key: "com.centurylinklabs.watchtower.enable"
        value: "true"
      - key: "traefik.enable"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.rule"
        value: "Host(`{{ service }}.{{ DOMAIN }}`)"
      - key: "traefik.http.routers.{{ service }}.service"
        value: "{{ service }}"
      - key: "traefik.http.routers.{{ service }}.entrypoints"
        value: "https"
      - key: "traefik.http.routers.{{ service }}.tls"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.tls.certresolver"
        value: "letsencrypt"
      - key: "traefik.http.services.{{ service }}.loadbalancer.server.port"
        value: "8083"

  hosts: all
  vars_files:
    - ../vars/vars.yml
    - ../vars/vault.yml

  tasks:
    - name: Start calibre web
      community.docker.docker_container:
        image: lscr.io/linuxserver/calibre-web:latest
        name: "{{ service }}"
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/Amsterdam"
          DOCKER_MODS: "linuxserver/mods:universal-calibre" # optional
          OAUTHLIB_RELAX_TOKEN_SCOPE: "1" # optional
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/config"
          - "{{ docker_nas_dir }}:/books"
        restart_policy: unless-stopped
        labels: "{{ labels | items2dict }}"
