---
- name: Vpn
  vars:
    service: "vpn"

  become: true
  hosts: all
  vars_files:
    - ../vars/vars.yml
    - ../vars/vault.yml

  tasks:
    - name: Check if scripts are up to date
      ansible.builtin.copy:
        src: ../local/WireGuard
        dest: "{{ home }}"
        mode: "0644"

    - name: Changing permissions of WireGuard script with +x
      ansible.builtin.file:
        dest: "{{ home }}/WireGuard/updateport.sh"
        mode: "a+x"

    - name: Set sysctl
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.src_valid_mark
        value: "1"
        state: present

    - name: Start vpn
      community.docker.docker_container:
        image: thrnz/docker-wireguard-pia:latest
        name: "{{ service }}"
        restart_policy: unless-stopped
        state: started
        volumes:
          - "{{ home }}:/pia-shared"
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        ports:
          # Sonarr
          - "8989:8989"
          # Radarr
          - "7878:7878"
          # Bazarr
          - "6767:6767"
          # "Readarr
          - "8787:8787"
          # "Prowlarr
          - "9696:9696"
          # "Calibre
          - "8081:8081"
          - "8083:8083"
          - "8181:8181"
          # "qbittorrent
          - "6881:6881"
          - "6881:6881/udp"
          - "8080:8080"
          - "4343:4343"
          # "Ombi
          - "3579:3579"
        env:
          LOC: poland
          USER: "{{ VPN_USER }}"
          PASS: "{{ VPN_PASS }}"
          PORT_FORWARDING: "1"
          QBT_USER: "{{ QBT_USER }}"
          QBT_PASS: "{{ QBT_PASS }}"
          QBT_HOST: "{{ QBT_HOST }}"
          PORT_SCRIPT: "/pia-shared/WireGuard/updateport.sh"
          LOCAL_NETWORK: "192.168.178.0/24"
          NFTABLES: "1"
          FIREWALL: "1"
        sysctls:
          # wg-quick fails to set this without --privileged, so set it here instead if needed
          # net.ipv4.conf.all.src_valid_mark: "1"
          net.ipv6.conf.default.disable_ipv6: "1"
          net.ipv6.conf.all.disable_ipv6: "1"
          net.ipv6.conf.lo.disable_ipv6: "1"
        labels:
          {
            "traefik.enable": "true",
            "autoheal-app": "true"
          }
        healthcheck:
          test: ping -c 1 www.google.com && pidof pf.sh || exit 1
          interval: 30s
          timeout: 10s
          retries: 3
      notify: Run command within the vpn container

  handlers:
    - name: Run command within the vpn container
      community.docker.docker_container_exec:
        container: "{{ service }}"
        command:
          /bin/sh -c "curl -c /mam.cookies -b 'mam_id={{ MAM_SESSION }}' https://t.myanonamouse.net/json/dynamicSeedbox.php"
