---
- name: Cooking
  hosts: all
  vars:
    service: "cooking"
    service_port: "80"
    service_labels: []

  vars_files:
    - ../vars/vault.yml
    - ../vars/traefik_labels.yml

  tasks:
    - name: Start cooking
      community.docker.docker_container:
        image: kick1999/cooking:latest
        name: "{{ service }}"
        restart_policy: "always"
        networks:
          - name: proxy
        labels: "{{ (traefik_public_labels + service_labels) | items2dict }}"
