---
- name: Flaresolverr
  vars:
    service: "flaresolverr"
    service_port: "8191"
    service_labels:
      - key: "autoheal-app"
        value: "true"

  hosts: all
  vars_files:
    - ../vars/vault.yml
    - ../vars/traefik_labels.yml

  tasks:
    - name: Start Flaresolverr
      community.docker.docker_container:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        name: "{{ service }}"
        env:
          TZ: Europe/Amsterdam
        network_mode: container:vpn
        restart_policy: unless-stopped
        labels: "{{ (traefik_default_labels + service_labels) | items2dict }}"
        state: healthy
        healthcheck:
          test: bash -c 'echo > /dev/tcp/localhost/8191 && echo > /dev/tcp/1.1.1.1/443'
          interval: 30s
          timeout: 15s
          start_period: 60s
