---
- name: Gatus
  vars:
    service: "gatus"
    service_port: "8080"
    service_labels: []

  hosts: all
  become: true
  vars_files:
    - ../vars/vault.yml
    - ../vars/traefik_labels.yml

  tasks:
    - name: Ensure gatus config dir exists
      ansible.builtin.file:
        path: "{{ docker_config_dir }}/{{ service }}"
        state: directory
        mode: "0755"

    - name: Deploy gatus configuration
      ansible.builtin.template:
        src: ../local/gatus/config.yaml
        dest: "{{ docker_config_dir }}/{{ service }}/config.yaml"
        mode: "0644"
      notify: Restart gatus

    - name: Set gatus host overrides
      ansible.builtin.set_fact:
        gatus_etc_hosts:
          "{{ 'sonarr.' + DOMAIN }}": host-gateway
          "{{ 'radarr.' + DOMAIN }}": host-gateway
          "{{ 'lidarr.' + DOMAIN }}": host-gateway
          "{{ 'prowlarr.' + DOMAIN }}": host-gateway
          "{{ 'bazarr.' + DOMAIN }}": host-gateway
          "{{ 'ombi.' + DOMAIN }}": host-gateway
          "{{ 'qbittorrent.' + DOMAIN }}": host-gateway
          "{{ 'calibre.' + DOMAIN }}": host-gateway
          "{{ 'prometheus.' + DOMAIN }}": host-gateway

    - name: Start gatus
      community.docker.docker_container:
        image: twinproduction/gatus:latest
        name: "{{ service }}"
        env:
          TZ: Europe/Amsterdam
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/config"
        restart_policy: unless-stopped
        networks:
          - name: proxy
        etc_hosts: "{{ gatus_etc_hosts }}"
        labels: "{{ (traefik_default_labels + service_labels) | items2dict }}"

  handlers:
    - name: Restart gatus
      community.docker.docker_container:
        name: "{{ service }}"
        restart: true
        state: started
