---
- name: Grafana
  vars:
    service: "grafana"
    labels:
      - key: "traefik.enable"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.rule"
        value: "Host(`{{ service }}.{{ DOMAIN }}`)"
      - key: "traefik.http.routers.{{ service }}.service"
        value: "{{ service }}"
      - key: "traefik.http.routers.{{ service }}.entrypoints"
        value: "https"
      - key: "traefik.http.routers.{{ service }}.tls"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.tls.certresolver"
        value: "letsencrypt"
      - key: "traefik.http.routers.{{ service }}.middlewares"
        value: "authelia"
      - key: "traefik.http.services.{{ service }}.loadbalancer.server.port"
        value: "3000"

  hosts: all
  vars_files:
    - ../vars/vars.yml
    - ../vars/vault.yml

  tasks:
    - name: Start grafana
      community.docker.docker_container:
        image: grafana/grafana:11.3.0
        name: "{{ service }}"
        user: "0:0"
        env:
          GF_AUTH_PROXY_ENABLED: "true"
          GF_AUTH_PROXY_HEADER_NAME: "Remote-User"
          GF_AUTH_PROXY_HEADER_PROPERTY: "username"
          GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
          GF_AUTH_PROXY_SYNC_TTL: "60"
          GF_AUTH_PROXY_HEADERS: "Name:Remote-Name Email:Remote-Email"
          GF_AUTH_DISABLE_LOGIN_FORM: "false"
          GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN: "true"
          GF_USERS_ALLOW_SIGN_UP: "false"
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/var/lib/grafana"
        restart_policy: unless-stopped
        networks:
          - name: proxy
        labels: "{{ labels | items2dict }}"
