---
- name: Grafana
  vars:
    service: "grafana"
    service_port: "3000"
    service_labels:
      - key: "wud.tag.semver"
        value: "true"

  hosts: all
  vars_files:
    - ../vars/vault.yml
    - ../vars/traefik_labels.yml

  tasks:
    - name: Start grafana
      community.docker.docker_container:
        image: grafana/grafana:13.1.0-25295570271-ubuntu
        name: "{{ service }}"
        user: "0:0"
        env:
          GF_AUTH_PROXY_ENABLED: "true"
          GF_AUTH_PROXY_HEADER_NAME: "Remote-User"
          GF_AUTH_PROXY_HEADER_PROPERTY: "username"
          GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
          GF_AUTH_PROXY_SYNC_TTL: "60"
          GF_AUTH_PROXY_HEADERS: "Name:Remote-Name Email:Remote-Email"
          GF_AUTH_DISABLE_LOGIN_FORM: "false"
          GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN: "true"
          GF_USERS_ALLOW_SIGN_UP: "false"
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/var/lib/grafana"
        restart_policy: unless-stopped
        networks:
          - name: proxy
        labels: "{{ (traefik_default_labels + service_labels) | items2dict }}"
