---
- name: Grocy
  vars:
    service: "grocy"
    service_port: "80"
    service_labels: []

  hosts: all
  vars_files:
    - ../vars/vault.yml
    - ../vars/traefik_labels.yml

  tasks:
    - name: Start grocy
      community.docker.docker_container:
        image: lscr.io/linuxserver/grocy:latest
        name: "{{ service }}"
        state: absent
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: Europe/Amsterdam
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/config"
        restart_policy: unless-stopped
        networks:
          - name: proxy
        labels: "{{ (traefik_default_labels + service_labels) | items2dict }}"
