---
- name: Homeassistant
  vars:
    service: "homeassistant"
    service_port: "8123"
    service_labels: []

  hosts: all
  become: true
  vars_files:
    - ../vars/vault.yml
    - ../vars/traefik_labels.yml

  tasks:
    - name: Adding yaml files
      ansible.builtin.template:
        src: ../local/homeassistant/{{ item }}
        dest: '{{ docker_config_dir }}/{{ service }}'
        mode: "0644"
      loop:
        - configuration.yaml


    - name: Start homeassistant
      community.docker.docker_container:
        image: "ghcr.io/home-assistant/home-assistant:latest"
        name: "{{ service }}"
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/config"
          - /etc/localtime:/etc/localtime:ro
        restart_policy: unless-stopped
        privileged: true
        ports:
          - 8123:8123
        networks:
          - name: proxy
        labels: "{{ (traefik_default_labels + service_labels) | items2dict }}"
