---
- name: LLDAP
  vars:
    service: "lldap"
    labels:
      - key: "traefik.enable"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.rule"
        value: "Host(`{{ service }}.{{ DOMAIN }}`)"
      - key: "traefik.http.routers.{{ service }}.service"
        value: "{{ service }}"
      - key: "traefik.http.routers.{{ service }}.entrypoints"
        value: "https"
      - key: "traefik.http.routers.{{ service }}.tls"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.tls.certresolver"
        value: "letsencrypt"
      - key: "traefik.http.routers.{{ service }}.middlewares"
        value: "authelia"
      - key: "traefik.http.services.{{ service }}.loadbalancer.server.port"
        value: "17170"
      - key: "wud.tag.semver"
        value: "true"

  hosts: all
  become: true
  vars_files:
    - ../vars/vars.yml
    - ../vars/vault.yml

  tasks:
    - name: Generate LLDAP JWT secret
      ansible.builtin.set_fact:
        lldap_jwt_secret: "{{ lookup('password', lookup('env', 'HOME') + '/.ansible/homelab-secrets/lldap_jwt_secret chars=ascii_letters,digits length=64') }}"
      no_log: true

    - name: Generate LLDAP admin password
      ansible.builtin.set_fact:
        lldap_admin_password: >-
          {{ lookup('password', lookup('env', 'HOME') +
             '/.ansible/homelab-secrets/lldap_admin_password chars=ascii_letters,digits length=32') }}
      no_log: true

    - name: Start lldap
      community.docker.docker_container:
        image: lldap/lldap:v0.6.2
        name: "{{ service }}"
        env:
          TZ: Europe/Amsterdam
          LLDAP_JWT_SECRET: "{{ lldap_jwt_secret }}"
          LLDAP_LDAP_BASE_DN: "dc={{ DOMAIN | replace('.', ',dc=') }}"
          LLDAP_LDAP_USER_PASS: "{{ lldap_admin_password }}"
          LLDAP_HTTP_URL: "https://{{ service }}.{{ DOMAIN }}"
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/data"
        restart_policy: unless-stopped
        networks:
          - name: proxy
        labels: "{{ labels | items2dict }}"
