---
- name: Loki
  vars:
    service: "loki"
    service_port: "3100"
    service_labels:
      - key: "prometheus.scrape"
        value: "true"
      - key: "prometheus.port"
        value: "3100"

  hosts: all
  become: true
  vars_files:
    - ../vars/vault.yml
    - ../vars/traefik_labels.yml

  tasks:
    - name: Ensure loki config dir exists
      ansible.builtin.file:
        path: "{{ docker_config_dir }}/{{ service }}"
        state: directory
        mode: "0755"

    - name: Deploy loki configuration
      ansible.builtin.template:
        src: ../local/loki/config.yaml
        dest: "{{ docker_config_dir }}/{{ service }}/config.yaml"
        mode: "0644"
      notify: Restart loki

    - name: Start loki
      community.docker.docker_container:
        image: grafana/loki:latest
        name: "{{ service }}"
        user: root
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/loki"
        command: -config.file=/loki/config.yaml
        restart_policy: unless-stopped
        networks:
          - name: proxy
        labels: "{{ (traefik_default_labels + service_labels) | items2dict }}"

  handlers:
    - name: Restart loki
      community.docker.docker_container:
        name: "{{ service }}"
        restart: true
        state: started
