---
- name: Loki
  vars:
    service: "loki"
    labels:
      - key: "traefik.enable"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.rule"
        value: "Host(`{{ service }}.{{ DOMAIN }}`)"
      - key: "traefik.http.routers.{{ service }}.service"
        value: "{{ service }}"
      - key: "traefik.http.routers.{{ service }}.entrypoints"
        value: "https"
      - key: "traefik.http.routers.{{ service }}.tls"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.tls.certresolver"
        value: "letsencrypt"
      - key: "traefik.http.routers.{{ service }}.middlewares"
        value: "authelia"
      - key: "traefik.http.services.{{ service }}.loadbalancer.server.port"
        value: "3100"
      - key: "prometheus.scrape"
        value: "true"
      - key: "prometheus.port"
        value: "3100"

  hosts: all
  become: true
  vars_files:
    - ../vars/vars.yml
    - ../vars/vault.yml

  tasks:
    - name: Ensure loki config dir exists
      ansible.builtin.file:
        path: "{{ docker_config_dir }}/{{ service }}"
        state: directory
        mode: "0755"

    - name: Deploy loki configuration
      ansible.builtin.template:
        src: ../local/loki/config.yaml
        dest: "{{ docker_config_dir }}/{{ service }}/config.yaml"
        mode: "0644"
      notify: Restart loki

    - name: Start loki
      community.docker.docker_container:
        image: grafana/loki:3.1.0
        name: "{{ service }}"
        user: root
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/loki"
        command: -config.file=/loki/config.yaml
        restart_policy: unless-stopped
        networks:
          - name: proxy
        labels: "{{ labels | items2dict }}"

  handlers:
    - name: Restart loki
      community.docker.docker_container:
        name: "{{ service }}"
        restart: true
        state: started
