---
- name: Nextcloud
  vars:
    service: "nextcloud"
    labels:
      - key: "com.centurylinklabs.watchtower.enable"
        value: "true"
      - key: "traefik.enable"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.rule"
        value: "Host(`{{ service }}.{{ DOMAIN }}`)"
      - key: "traefik.http.routers.{{ service }}.service"
        value: "{{ service }}"
      - key: "traefik.http.routers.{{ service }}.entrypoints"
        value: "https"
      - key: "traefik.http.routers.{{ service }}.tls"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.tls.certresolver"
        value: "letsencrypt"
      - key: "traefik.http.services.{{ service }}.loadbalancer.server.port"
        value: "8080"

  hosts: all
  vars_files:
    - ../vars/vars.yml
    - ../vars/vault.yml

  tasks:
    - name: Create docker volume
      community.docker.docker_volume:
        volume_name: nextcloud_aio_mastercontainer # This line is not allowed to be changed as otherwise the built-in backup solution will not workb

    - name: Start nextcloud
      community.docker.docker_container:
        image: nextcloud/all-in-one:latest
        init: true
        state: absent
        hostname: "{{ service }}.{{ DOMAIN }}"
        name: nextcloud-aio-mastercontainer
        env:
          APACHE_PORT: "11000"
          APACHE_IP_BINDING: "127.0.0.1"
        volumes:
          # This line is not allowed to be changed as otherwise the built-in backup solution will not work
          - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
          - /var/run/docker.sock:/var/run/docker.sock:ro
        restart_policy: unless-stopped
        ports:
          - 8443:8080
          - 11000:11000
        labels: "{{ labels | items2dict }}"
