---
- vars:
    service: "prometheus"
    labels:
    - key: "com.centurylinklabs.watchtower.enable"
      value: "true"
    - key: "traefik.enable"
      value: "true"
    - key: "traefik.http.routers.{{ service }}.rule"
      value: "Host(`{{ service }}.{{ DOMAIN }}`)"
    - key: "traefik.http.routers.{{ service }}.service"
      value: "{{ service }}"
    - key: "traefik.http.routers.{{ service }}.entrypoints"
      value: "https"
    - key: "traefik.http.routers.{{ service }}.tls"
      value: "true"
    - key: "traefik.http.routers.{{ service }}.tls.certresolver"
      value: "letsencrypt"
    - key: "traefik.http.services.{{ service }}.loadbalancer.server.port"
      value: "9090"

  hosts: all
  become: true
  vars_files: 
    - ../vars/vars.yml
    - ../vars/vault.yml

  tasks:
    - name: Adding yaml files
      template:
        src: ../local/prometheus/{{ item }}
        dest: '{{ docker_config_dir }}/prometheus-etc/{{ item }}'
      loop:
        - prometheus.yml

    - name: Start prometheus
      docker_container:
        image: prom/prometheus:latest
        name: "{{ service }}"
        user: root
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/prometheus"
          - "{{ docker_config_dir }}/prometheus-etc:/etc/prometheus"
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: unless-stopped
        network_mode: container:vpn
        labels: "{{ labels | items2dict}}"
