---
- name: Prometheus
  vars:
    service: "prometheus"
    service_port: "9090"
    service_labels:
      - key: "autoheal-app"
        value: "true"

  hosts: all
  become: true
  vars_files:
    - ../vars/vault.yml
    - ../vars/traefik_labels.yml

  tasks:
    - name: Adding yaml files
      ansible.builtin.template:
        src: ../local/prometheus/{{ item }}
        dest: '{{ docker_config_dir }}/prometheus-etc/{{ item }}'
        mode: "0644"
      loop:
        - prometheus.yml
      notify: Restart prometheus

    - name: Start prometheus
      community.docker.docker_container:
        image: prom/prometheus:latest
        name: "{{ service }}"
        user: root
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/prometheus"
          - "{{ docker_config_dir }}/prometheus-etc:/etc/prometheus"
          - /var/run/docker.sock:/var/run/docker.sock
        command:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--storage.tsdb.retention.time=30d"
          - "--storage.tsdb.retention.size=5GB"
        restart_policy: unless-stopped
        network_mode: container:vpn
        state: healthy
        labels: "{{ (traefik_default_labels + service_labels) | items2dict }}"
        healthcheck:
          test: sh -c 'wget -q --spider http://localhost:9090/-/healthy && wget -q -T 10 --tries=1 --spider http://1.1.1.1'
          interval: 30s
          timeout: 15s
          start_period: 60s

  handlers:
    - name: Restart prometheus
      community.docker.docker_container:
        name: "{{ service }}"
        restart: true
        state: started
