---
- name: Prometheus
  vars:
    service: "prometheus"
    labels:
      - key: "traefik.enable"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.rule"
        value: "Host(`{{ service }}.{{ DOMAIN }}`)"
      - key: "traefik.http.routers.{{ service }}.service"
        value: "{{ service }}"
      - key: "traefik.http.routers.{{ service }}.entrypoints"
        value: "https"
      - key: "traefik.http.routers.{{ service }}.tls"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.tls.certresolver"
        value: "letsencrypt"
      - key: "traefik.http.routers.{{ service }}.middlewares"
        value: "authelia"
      - key: "traefik.http.services.{{ service }}.loadbalancer.server.port"
        value: "9090"
      - key: "autoheal-app"
        value: "true"
      - key: "wud.tag.semver"
        value: "true"

  hosts: all
  become: true
  vars_files:
    - ../vars/vars.yml
    - ../vars/vault.yml

  tasks:
    - name: Adding yaml files
      ansible.builtin.template:
        src: ../local/prometheus/{{ item }}
        dest: '{{ docker_config_dir }}/prometheus-etc/{{ item }}'
        mode: "0644"
      loop:
        - prometheus.yml
      notify: Restart prometheus

    - name: Start prometheus
      community.docker.docker_container:
        image: prom/prometheus:v3.11.3
        name: "{{ service }}"
        user: root
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/prometheus"
          - "{{ docker_config_dir }}/prometheus-etc:/etc/prometheus"
          - /var/run/docker.sock:/var/run/docker.sock
        command:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--storage.tsdb.retention.time=30d"
          - "--storage.tsdb.retention.size=5GB"
        restart_policy: unless-stopped
        network_mode: container:vpn
        state: healthy
        labels: "{{ labels | items2dict }}"
        healthcheck:
          test: wget -q --spider http://localhost:9090/-/healthy
          interval: 30s
          timeout: 10s
          start_period: 60s

  handlers:
    - name: Restart prometheus
      community.docker.docker_container:
        name: "{{ service }}"
        restart: true
        state: started
