---
- name: Qbittorrent
  vars:
    service: "qbittorrent"
    labels:
      - key: "com.centurylinklabs.watchtower.enable"
        value: "true"
      - key: "traefik.enable"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.rule"
        value: "Host(`{{ service }}.{{ DOMAIN }}`)"
      - key: "traefik.http.routers.{{ service }}.service"
        value: "{{ service }}"
      - key: "traefik.http.routers.{{ service }}.entrypoints"
        value: "https"
      - key: "traefik.http.routers.{{ service }}.middlewares"
        value: "auth"
      - key: "traefik.http.routers.{{ service }}.tls"
        value: "true"
      - key: "traefik.http.routers.{{ service }}.tls.certresolver"
        value: "letsencrypt"
      - key: "traefik.http.services.{{ service }}.loadbalancer.server.port"
        value: "4343"

  hosts: all
  vars_files:
    - ../vars/vars.yml
    - ../vars/vault.yml

  tasks:
    - name: Start qbittorrent
      community.docker.docker_container:
        image: linuxserver/qbittorrent:latest
        name: "{{ service }}"
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: Europe/Amsterdam
          WEBUI_PORT: "4343"
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/config"
          - "{{ docker_nas_dir }}/Download:/downloads"
        restart_policy: unless-stopped
        network_mode: container:vpn
        labels: "{{ labels | items2dict }}"
        state: healthy
        healthcheck:
          test: curl -f {{ service }}.{{ DOMAIN }}
          interval: 30s
          timeout: 10s
