---
- name: Radarr
  vars:
    service: "radarr"
    service_port: "7878"
    service_labels:
      - key: "autoheal-app"
        value: "true"

  hosts: all
  vars_files:
    - ../vars/vault.yml
    - ../vars/traefik_labels.yml

  tasks:
    - name: Start radarr
      community.docker.docker_container:
        image: lscr.io/linuxserver/radarr:latest
        name: "{{ service }}"
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: Europe/Amsterdam
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/config"
          - "{{ docker_nas_dir }}:/movies"
          - "{{ docker_nas_dir }}/Download:/downloads"
        restart_policy: unless-stopped
        state: healthy
        network_mode: container:vpn
        labels: "{{ (traefik_default_labels + service_labels) | items2dict }}"
        healthcheck:
          test: bash -c 'echo > /dev/tcp/localhost/7878 && echo > /dev/tcp/1.1.1.1/443'
          interval: 30s
          timeout: 15s
          start_period: 60s

    - name: Set radarr authentication to external
      ansible.builtin.replace:
        path: "{{ docker_config_dir }}/{{ service }}/config.xml"
        regexp: '<AuthenticationMethod>.*</AuthenticationMethod>'
        replace: '<AuthenticationMethod>External</AuthenticationMethod>'
      notify: Restart radarr

  handlers:
    - name: Restart radarr
      community.docker.docker_container:
        name: "{{ service }}"
        restart: true
        state: started
