---
- vars:
    service: "readarr"
    labels:
    - key: "com.centurylinklabs.watchtower.enable"
      value: "true"
    - key: "traefik.enable"
      value: "true"
    - key: "traefik.http.routers.{{ service }}.rule"
      value: "Host(`{{ service }}.{{ DOMAIN }}`)"
    - key: "traefik.http.routers.{{ service }}.service"
      value: "{{ service }}"
    - key: "traefik.http.routers.{{ service }}.entrypoints"
      value: "https"
    - key: "traefik.http.routers.{{ service }}.tls"
      value: "true"
    - key: "traefik.http.routers.{{ service }}.tls.certresolver"
      value: "letsencrypt"
    - key: "traefik.http.services.{{ service }}.loadbalancer.server.port"
      value: "8787"
    - key: "autoheal-app"
      value: "true"

  hosts: all
  vars_files: 
    - ../vars/vars.yml
    - ../vars/vault.yml

  tasks:
    - name: Start readarr
      docker_container:
        image: linuxserver/readarr:nightly
        name: "{{ service }}"
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: Europe/Amsterdam
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/config"
          - "{{ docker_nas_dir }}:/books"
          - "{{ docker_nas_dir }}/Download:/downloads"
        network_mode: container:vpn
        restart_policy: unless-stopped
        labels: "{{ labels | items2dict}}"
        healthcheck:
          test: ping -c 1 www.google.com && pidof pf.sh || exit 1
          interval: 180s
          timeout: 10s
          retries: 3
