---
- name: Sonarr
  vars:
    service: "sonarr"
    service_port: "8989"
    service_labels:
      - key: "autoheal-app"
        value: "true"
      - key: "wud.tag.include"
        value: '^v?\d+\.\d+\.\d+(\.\d+)?(-r\d+)?-ls\d+$'

  hosts: all
  vars_files:
    - ../vars/vault.yml
    - ../vars/traefik_labels.yml

  tasks:
    - name: Start Sonarr
      community.docker.docker_container:
        image: linuxserver/sonarr:4.0.17.2952-ls306
        name: "{{ service }}"
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: Europe/Amsterdam
        volumes:
          - "{{ docker_config_dir }}/{{ service }}:/config"
          - "{{ docker_nas_dir }}:/tv"
          - "{{ docker_nas_dir }}/Download:/downloads"
        restart_policy: always
        network_mode: container:vpn
        state: healthy
        labels: "{{ (traefik_default_labels + service_labels) | items2dict }}"
        healthcheck:
          test: bash -c 'echo > /dev/tcp/localhost/8989'
          interval: 30s
          timeout: 10s
          start_period: 60s

    - name: Set sonarr authentication to external
      ansible.builtin.replace:
        path: "{{ docker_config_dir }}/{{ service }}/config.xml"
        regexp: '<AuthenticationMethod>.*</AuthenticationMethod>'
        replace: '<AuthenticationMethod>External</AuthenticationMethod>'
      notify: Restart sonarr

  handlers:
    - name: Restart sonarr
      community.docker.docker_container:
        name: "{{ service }}"
        restart: true
        state: started
