---
- name: Traefik
  vars:
    service: "traefik"
    labels:
      - key: "traefik.enable"
        value: "true"
      - key: "traefik.http.middlewares.authelia.forwardauth.address"
        value: "http://authelia:9091/api/authz/forward-auth"
      - key: "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader"
        value: "true"
      - key: "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders"
        value: "Remote-User,Remote-Groups,Remote-Name,Remote-Email"
      - key: "traefik.http.routers.{{ service }}.rule"
        value: "Host(`{{ service }}.{{ DOMAIN }}`)"
      - key: "traefik.http.routers.{{ service }}.service"
        value: "api@internal"
      - key: "traefik.http.routers.{{ service }}.middlewares"
        value: "authelia"

  hosts: all
  become: true
  vars_files:
    - ../vars/vars.yml
    - ../vars/vault.yml

  tasks:
    - name: Ensures traefik dir exists
      ansible.builtin.file:
        path: "{{ traefik }}"
        state: directory
        mode: "0644"

    - name: Ensures acme.json file exists
      ansible.builtin.copy:
        content: ""
        dest: "{{ traefik }}/acme.json"
        mode: "0600"
        force: false

    - name: Adding traefik.yml file
      ansible.builtin.template:
        src: ../local/traefik/traefik.yml
        dest: "{{ traefik }}/traefik.yml"
        mode: "0600"

    - name: Create proxy network
      community.docker.docker_network:
        name: proxy
        state: present

    - name: Starting the reverse proxy.
      community.docker.docker_container:
        name: "{{ service }}"
        image: traefik:v3.3
        restart_policy: always
        state: started
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - "{{ traefik }}/acme.json:/letsencrypt/acme.json"
          - "{{ traefik }}{{ traefik_file }}:/etc/traefik/traefik.yml"
        networks:
          - name: proxy
        labels: "{{ labels | items2dict }}"
