---
- name: Watchtower
  vars:
    service: "watchtower"

  hosts: all
  vars_files:
    - ../vars/vars.yml
    - ../vars/vault.yml

  tasks:
    - name: Start watchtower
      community.docker.docker_container:
        image: containrrr/watchtower:latest
        name: "{{ service }}"
        command: --cleanup --label-enable --interval 3600
        labels:
          {
            "com.centurylinklabs.watchtower.enable": "true",
            "traefik.enable": "true",
          }
        restart_policy: always
        network_mode: none
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
