---
theme: auto

server:
  address: 'tcp://0.0.0.0:9091'

log:
  level: info

totp:
  issuer: '{{ DOMAIN }}'

identity_validation:
  reset_password:
    jwt_secret: '{{ authelia_jwt_secret }}'

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      argon2:
        iterations: 3
        memory: 65536
        parallelism: 4

access_control:
  default_policy: two_factor

session:
  secret: '{{ authelia_session_secret }}'
  cookies:
    - name: authelia_session
      domain: '{{ DOMAIN }}'
      authelia_url: 'https://authelia.{{ DOMAIN }}'
      default_redirection_url: 'https://{{ DOMAIN }}'
      expiration: 30d
      inactivity: 7d
      remember_me: 90d

storage:
  encryption_key: '{{ authelia_storage_key }}'
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

identity_providers:
  oidc:
    hmac_secret: '{{ authelia_oidc_hmac }}'
    jwks:
      - key_id: 'default'
        algorithm: 'RS256'
        use: 'sig'
        key: |
          {{ authelia_oidc_private_key | indent(10) }}
    clients:
      - client_id: wud
        client_name: "What's Up Docker"
        client_secret: '{{ authelia_oidc_wud_secret_hash }}'
        public: false
        authorization_policy: two_factor
        redirect_uris:
          - 'https://wud.{{ DOMAIN }}/auth/oidc/authelia/cb'
        scopes:
          - openid
          - profile
          - email
        userinfo_signed_response_alg: none
