---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: https://jellyfin.tstultiens.com/
        description: Series management
        siteMonitor: https://jellyfin.tstultiens.com/
        widget:
          type: jellyfin
          url: https://jellyfin.tstultiens.com
          key: {{jellyfin_apikey}}
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
    - Ombi:
        icon: ombi.png
        href: https://ombi.tstultiens.com/
        description: Series management
        siteMonitor: https://ombi.tstultiens.com/
        widget:
          type: ombi
          url: https://ombi.tstultiens.com
          key: {{ombi_apikey}}
    - Calibre:
        icon: calibre.png
        href: https://calibre.tstultiens.com/
        description: Series management
        siteMonitor: https://calibre.tstultiens.com/
    - Calibre-Web:
        icon: calibre-web.png
        href: https://calibre-web.tstultiens.com/
        description: Series management
        siteMonitor: https://calibre-web.tstultiens.com/
        widget:
          type: calibreweb
          url: https://calibre-web.tstultiens.com
          username: {{calibreweb_username}}
          password: {{calibreweb_password}}

- Sourcers:
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.tstultiens.com/
        description: Series management
        siteMonitor: https://sonarr.tstultiens.com/
        widget:
          type: sonarr
          url: https://sonarr.tstultiens.com
          key: {{sonarr_apikey}}
          enableQueue: true # optional, defaults to false
    - Radarr:
        icon: radarr.png
        href: https://radarr.tstultiens.com/
        description: Movie management
        siteMonitor: https://radarr.tstultiens.com/
        widget:
          type: radarr
          url: https://radarr.tstultiens.com
          key: {{radarr_apikey}}
          enableQueue: true # optional, defaults to false
    - Readarr:
        icon: readarr.png
        href: https://readarr.tstultiens.com/
        description: Movie management
        siteMonitor: https://readarr.tstultiens.com/
        widget:
          type: readarr
          url: https://readarr.tstultiens.com
          key: {{readarr_apikey}}

    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.tstultiens.com/
        description: Movie management
        siteMonitor: https://prowlarr.tstultiens.com/
        widget:
          type: prowlarr
          url: https://prowlarr.tstultiens.com
          key: {{prowlarr_apikey}}

    - Lidarr:
        icon: lidarr.png
        href: https://lidarr.tstultiens.com/
        description: Movie management
        siteMonitor: https://lidarr.tstultiens.com/
        widget:
          type: lidarr
          url: https://lidarr.tstultiens.com
          key: {{lidarr_apikey}}
    - Tdarr:
        icon: tdarr.png
        href: https://tdarr.tstultiens.com/
        description: Movie management
        siteMonitor: https://tdarr.tstultiens.com/
        widget:
          type: tdarr
          url: https://tdarr.tstultiens.com
