---
- name: Ensure python-requests is installed.
  ansible.builtin.package:
    name: python-requests
    state: present

- name: Ensure python-docker is installed.
  ansible.builtin.package:
    name: python-docker
    state: present

- name: Ensure docker is installed.
  ansible.builtin.package:
    name: docker
    state: present

- name: Ensure docker-compose is installed.
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure docker is running.
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  register: docker_add_to_docker_group_result

- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta: reset_connection
  when: docker_add_to_docker_group_result
